apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
        - name: account-service
          image: zia7770/account-service:latest
          ports:
            - containerPort: 8082
          env:
            - name: TRANSACTION_SERVICE_URL
              value: "http://transaction-service:8081"

---
apiVersion: v1
kind: Service
metadata:
  name: account-service
spec:
  selector:
    app: account-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP