name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean install

  dockerize:
    name: Docker Build and Push
    needs: build-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push account-service Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/account-service:latest ./account-service
          docker push ${{ secrets.DOCKER_USERNAME }}/account-service:latest

      - name: Build and Push transaction-service Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/transaction-service:latest ./transaction-service
          docker push ${{ secrets.DOCKER_USERNAME }}/transaction-service:latest

      - name: Build and Push ui-service Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ui-service:latest ./ui-service
          docker push ${{ secrets.DOCKER_USERNAME }}/ui-service:latest
