name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean install

      - name: Save Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            account-service/target/*.jar
            transaction-service/target/*.jar

  dockerize:
    name: Docker Build and Push
    needs: build-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push account-service Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/account-service:latest ./account-service
          docker push ${{ secrets.DOCKER_USERNAME }}/account-service:latest

      - name: Build and Push transaction-service Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/transaction-service:latest ./transaction-service
          docker push ${{ secrets.DOCKER_USERNAME }}/transaction-service:latest

  deploy:
    runs-on: [self-hosted, wsl-runner-assignment]  # Specify self-hosted runner here
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to Minikube
        run: |
          kubectl apply -f ${{ github.workspace }}/transaction-service/k8s/transaction-service.yaml
          kubectl apply -f ${{ github.workspace }}/account-service/k8s/account-service.yaml